name: default

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pip=21.3.1
  - ipykernel=6.7.0
  - pip:
    - torch==1.10.1
    - fire==0.3.1
    - autopep8==1.6.0
    - click==8.0.3
    - meson>=0.55
    - toml>=0.10
    - jinja2==3.0.3
    - numpy==1.13.1